### ISSUE TITLE
Scraper returns only 20 messages maximum

### ISSUE THREAD

**Issue by sh0tx420** [nuzulul/telegram-scraper#2]
I've looked into this and it seems that the HTML string returned by https.get() contains only 20 message divs.
I have no idea how this could be fixed, so if you want to fix it, I cant help, sorry 😄
But I would want to get more than 20 messages at once.

**Comment by nuzulul** [comment]
Yes, that is a limitation of using this method. Currently, you can get more than 20 messages using the [Telegram API](https://core.telegram.org/).
